export const characters = [
    {label:'0', character:'অ/য়', image:'0.jpg'},
    {label:'1', character:'আ/া', image:'1.jpg'},
    {label:'2', character:'ই/ঈ/ি/ী', image:'2.jpg'},
    {label:'3', character:'উ/ঊ/ু/ূ', image:'3.jpg'},
    {label:'4', character:'ঋ/র/ড়/ঢ়/ৃ', image:'4.jpg'},
    {label:'5', character:'এ/ে', image:'5.jpg'},
    {label:'6', character:'ঐ/ৈ', image:'6.jpg'},
    {label:'7', character:'ও/ো', image:'7.jpg'},
    {label:'8', character:'ঔ/ৌ', image:'8.jpg'},
    {label:'9', character:'ক', image:'9.jpg'},
    {label:'10', character:'খ/ক্ষ', image:'10.jpg'},
    {label:'11', character:'গ', image:'11.jpg'},
    {label:'12', character:'ঘ', image:'12.jpg'},
    {label:'13', character:'ঙ', image:'13.jpg'},
    {label:'14', character:'চ', image:'14.jpg'},
    {label:'15', character:'ছ', image:'15.jpg'},
    {label:'16', character:'জ/য', image:'16.jpg'},
    {label:'17', character:'ঝ', image:'16.jpg'},
    {label:'18', character:'ঞ', image:'18.jpg'},
    {label:'19', character:'ট', image:'19.jpg'},
    {label:'20', character:'ঠ', image:'20.jpg'},
    {label:'21', character:'ড', image:'21.jpg'},
    {label:'22', character:'ঢ', image:'22.jpg'},
    {label:'23', character:'ন/ণ', image:'23.jpg'},
    {label:'24', character:'ত/ৎ', image:'24.jpg'},
    {label:'25', character:'থ', image:'25.jpg'},
    {label:'26', character:'দ', image:'26.jpg'},
    {label:'27', character:'ধ', image:'27.jpg'},
    {label:'28', character:'প', image:'28.jpg'},
    {label:'29', character:'ফ', image:'29.jpg'},
    {label:'30', character:'ব/ভ', image:'30.jpg'},
    {label:'31', character:'ম', image:'31.jpg'},
    {label:'32', character:'ল', image:'32.jpg'},
    {label:'33', character:'শ/স/ষ', image:'33.jpg'},
    {label:'34', character:'হ', image:'34.jpg'},
    {label:'35', character:'ং', image:'35.jpg'},
    {label:'37', character:'(ঁ)', image:'37.jpg'},
]

export const words = [
    {label:'aaj', character:'আজ', image:'aaj.jpg'},
    {label:'ami', character:'আমি', image:'ami.jpg'},
    {label:'ashirbad', character:'আশির্বাদ', image:'ashirbad.jpg'},
    {label:'badha', character:'বাধা', image:'badha.jpg'},
    {label:'bagh', character:'বাঘ', image:'bagh.jpg'},
    {label:'bati', character:'বাটি', image:'bati.jpg'},
    {label:'bondhu', character:'বন্ধু', image:'bondhu.jpg'},
    {label:'goyendha', character:'গোয়েন্দা', image:'goyendha.jpg'},
    {label:'puru', character:'পুরু', image:'puru.jpg'},
    {label:'tahara', character:'তাঁহারা', image:'tahara.jpg'},
]

export const digits = [
    { label: 'zero', character: '০', image: 'zero.jpg' },
    { label: 'one', character: '১', image: 'one.jpg' },
    { label: 'two', character: '২', image: 'two.jpg' },
    { label: 'three', character: '৩', image: 'three.jpg' },
    { label: 'four', character: '৪', image: 'four.jpg' },
    { label: 'five', character: '৫', image: 'five.jpg' },
    { label: 'six', character: '৬', image: 'six.jpg' },
    { label: 'seven', character: '৭', image: 'seven.jpg' },
    { label: 'eight', character: '৮', image: 'eight.jpg' },
    { label: 'nine', character: '৯', image: 'nine.jpg' },
  ];
  